// Source file: com/allaire/wddx/WddxDeserializer.java

package com.allaire.wddx;


import org.xml.sax.InputSource;
import java.io.IOException;


/**
 * Provides WDDX deserialization services
 *
 * <p>The class processes WDDX packets via the org.xml.sax.InputSource
 * interface and returns the top-level deserialized object</p>
 *
 * @author Simeon Simeonov (simeons@allaire.com)
 * @version 1.0
 * @see com.allaire.wddx.DeserializerWorker
 */
public class WddxDeserializer 
{
    ///////////////////////////////////////////////////////////////////////
    //
    // Implementation data
    //
    ///////////////////////////////////////////////////////////////////////


    private static final String DEFAULT_SAX_CLASS_PROPERTY = "org.xml.sax.parser";

    private DeserializerWorker m_worker = null;
        
    
    ///////////////////////////////////////////////////////////////////////
    //
    // Construction/Finalization
    //
    ///////////////////////////////////////////////////////////////////////


    /**
     * Construct a WDDX deserializer object using the default SAX parser.
     *
     * <p>The default SAX parser class name is obtained from the 
     * 'org.xml.sax.parser' system property. The class must exist and
     * implement the org.xml.sax.Parser interface.</p>
     *
     * @exception com.allaire.wddx.WddxDeserializationException A WDDX exception, possibly
     *            wrapping a ClassNotFoundException, NullPointerException, 
     *            ClassCastException, IllegalAccessException, or an 
     *            Instantiation exception.
     * @see org.xml.sax.Parser
     */
    public WddxDeserializer() throws WddxDeserializationException
    {
        String parserClass = System.getProperty(DEFAULT_SAX_CLASS_PROPERTY);
        if (parserClass == null) 
        {
            String errorMessage = "No value for " +  DEFAULT_SAX_CLASS_PROPERTY + " property.";
            throw new WddxDeserializationException(
                errorMessage,
                new NullPointerException(errorMessage)                
                );
        }
        
        constructDeserializationWorker(parserClass);
    }


    /**
     * Construct a WDDX serializer object using the specified SAX parser.
     *
     * <p>The specified class must exist and implement the org.xml.sax.Parser 
     * interface.</p>
     *
     * @param parserClass The name of the SAX parser class.
     * @exception com.allaire.wddx.WddxDeserializationException A WDDX exception, possibly
     *            wrapping a ClassNotFoundException, NullPointerException, 
     *            ClassCastException, IllegalAccessException, or an 
     *            Instantiation exception.
     * @see org.xml.sax.Parser
     */
    public WddxDeserializer(String parserClass) throws WddxDeserializationException
    {
        constructDeserializationWorker(parserClass);        
    }
    
    
    ///////////////////////////////////////////////////////////////////////
    //
    // Operations
    //
    ///////////////////////////////////////////////////////////////////////


    /**
     * Deserializes the contents of a WDDX packet
     *  
     * @return Top-level object in WDDX packet
     * @param source The WDDX packet to process
     * @exception com.allaire.wddx.WddxDeserializationException
     *      Any WDDX deserialization exception, possibly wrapping another exception
     * @exception java.lang.IOException
     *      Any I/O exception that may have been generated by the source parameter
     * @see org.xml.sax.InputSource
     * @see com.allaire.wddx.WddxDeserializer
     */
    public Object deserialize(InputSource source) throws WddxDeserializationException, IOException
    {
        return m_worker.deserialize(source);
    }

    
    ///////////////////////////////////////////////////////////////////////
    //
    // Helper functions
    //
    ///////////////////////////////////////////////////////////////////////


    /**
     * Construct a WDDX deserialization worker using a specified SAX parser.
     *
     * <p>The specified class must exist and implement the org.xml.sax.Parser 
     * interface.</p>
     *
     * @param parserClass The name of the SAX parser class.
     * @exception com.allaire.wddx.WddxDeserializationException A WDDX exception, possibly
     *            wrapping a ClassNotFoundException, NullPointerException, 
     *            ClassCastException, IllegalAccessException, or an 
     *            Instantiation exception.
     * @see com.allaire.wddx.WddxDeserializer#WddxDeserializer
     * @see com.allaire.wddx.DeserializerWorker
     * @see org.xml.sax.Parser
     */
    private void constructDeserializationWorker(String parserClass) throws WddxDeserializationException
    {
        m_worker = new DeserializerWorker(parserClass);
        if (m_worker == null)
        {
            String errorMessage = "Cannot instantiate WDDX deserializer.";
            throw new WddxDeserializationException(
                errorMessage,
                new NullPointerException(errorMessage)                
                );
        }
    }    
}
