package com.lrc.playpen;


/*
 * Dire.java
 *
 * Created on March 24, 2001, 10:15 PM
 */

/**
 * DOCUMENT ME!
 *
 * @author root
 * @version
 */
public class Dire extends javax.swing.JDialog {
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel line1Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jButton2;
    private javax.swing.JToggleButton jToggleButton2;
    private com.lrc.market.charts.BasicChart basicChart2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jButton3;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JLabel jLabel1;
    private com.lrc.market.charts.BasicChart basicChart1;

    /**
     * Creates new form Dire
     *
     * @param parent DOCUMENT ME!
     * @param modal DOCUMENT ME!
     */
    public Dire(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //pack ();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * FormEditor.
     */
    private void initComponents() //GEN-BEGIN:initComponents
     {
        centerPanel = new javax.swing.JPanel();
        line1Panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        basicChart2 = new com.lrc.market.charts.BasicChart();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jToggleButton4 = new javax.swing.JToggleButton();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        basicChart1 = new com.lrc.market.charts.BasicChart();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }
            });

        centerPanel.setLayout(new javax.swing.BoxLayout(centerPanel, 1));

        line1Panel.setLayout(new javax.swing.BoxLayout(line1Panel, 0));
        line1Panel.setBorder(new javax.swing.border.SoftBevelBorder(0));

        jButton1.setText("jButton1");
        line1Panel.add(jButton1);

        jToggleButton1.setBorder(null);
        jToggleButton1.setText("jToggleButton1");
        line1Panel.add(jToggleButton1);

        centerPanel.add(line1Panel);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, 0));
        jPanel3.setBorder(new javax.swing.border.TitledBorder("Testing"));

        jButton2.setText("jButton1");
        jPanel3.add(jButton2);

        jToggleButton2.setText("jToggleButton1");
        jPanel3.add(jToggleButton2);

        basicChart2.setLayout(new java.awt.BorderLayout());
        jPanel3.add(basicChart2);

        centerPanel.add(jPanel3);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, 0));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(1, 1, 1, 1,
                                                             java.awt.Color.black));

        jButton3.setText("jButton1");
        jPanel4.add(jButton3);

        jToggleButton3.setText("jToggleButton1");
        jPanel4.add(jToggleButton3);

        centerPanel.add(jPanel4);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        jToggleButton4.setText("jToggleButton4");
        jPanel5.add(jToggleButton4);

        getContentPane().add(jPanel5, java.awt.BorderLayout.EAST);

        getContentPane().add(jSlider1, java.awt.BorderLayout.NORTH);

        getContentPane().add(jSlider2, java.awt.BorderLayout.SOUTH);

        jLabel1.setText("jLabel1");

        getContentPane().add(jLabel1, java.awt.BorderLayout.WEST);

        basicChart1.setLayout(new java.awt.BorderLayout());

        getContentPane().add(basicChart1, java.awt.BorderLayout.NORTH);
    }

    //GEN-END:initComponents

    /**
     * Closes the dialog
     *
     * @param evt DOCUMENT ME!
     */
    private void closeDialog(java.awt.event.WindowEvent evt) { //GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }

    //GEN-LAST:event_closeDialog

    /**
     * DOCUMENT ME!
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new Dire(new javax.swing.JFrame(), true).show();
    }

    // End of variables declaration//GEN-END:variables
}
