/*
 * Lurk.java
 *
 * Created on March 24, 2001, 5:39 AM
 */
package com.lrc.playpen;

/**
 * DOCUMENT ME!
 *
 * @author root
 * @version
 */
public class Lurk extends java.awt.Dialog {
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton okButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JSeparator seperator;

    /**
     * Creates new form Dialog
     *
     * @param parent DOCUMENT ME!
     * @param modal DOCUMENT ME!
     */
    public Lurk(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pack();
    }

    /**
     * This method is called from within the init() method to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    private void initComponents() //GEN-BEGIN:initComponents
     {
        popupMenu = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        seperator = new javax.swing.JSeparator();

        jMenuItem1.setText("Item");
        popupMenu.add(jMenuItem1);
        setForeground(java.awt.Color.orange);
        setFont(new java.awt.Font("Arial", 1, 10));
        setBackground(java.awt.Color.lightGray);
        setTitle("Lurker");
        setName("Lurker");
        addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosing(java.awt.event.WindowEvent evt) {
                    closeDialog(evt);
                }

                public void windowClosed(java.awt.event.WindowEvent evt) {
                    formWindowClosed(evt);
                }
            });

        okButton.setToolTipText("The OK Button");
        okButton.setFont(new java.awt.Font("Arial", 1, 10));
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    okButton_actionPerformed(evt);
                }
            });

        add(okButton);
        okButton.setBounds(50, 210, 90, 40);

        cancelButton.setFont(new java.awt.Font("Arial", 1, 10));
        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cancelButtonActionPerformed(evt);
                }
            });

        add(cancelButton);
        cancelButton.setBounds(360, 210, 110, 40);

        add(seperator);
        seperator.setBounds(0, 190, 580, seperator.getPreferredSize().height);

        pack();

        java.awt.Dimension screenSize =
            java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setSize(new java.awt.Dimension(500, 300));
        setLocation((screenSize.width-500)/2, (screenSize.height-300)/2);
    }
     //GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_cancelButtonActionPerformed

        // Add your handling code here:
    }
     //GEN-LAST:event_cancelButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) { //GEN-FIRST:event_formWindowClosed

        // Add your handling code here:
    }
     //GEN-LAST:event_formWindowClosed

    private void okButton_actionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_okButton_actionPerformed

        // Add your handling code here:
    }
     //GEN-LAST:event_okButton_actionPerformed

    /**
     * Closes the dialog
     *
     * @param evt DOCUMENT ME!
     */
    private void closeDialog(java.awt.event.WindowEvent evt) { //GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }
     //GEN-LAST:event_closeDialog

    /**
     * DOCUMENT ME!
     *
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new Lurk(new java.awt.Frame(), true).setVisible(true);
        System.out.println("Lurk Started.");
    }

    // End of variables declaration//GEN-END:variables
}
