package com.lrc.soap;

import java.awt.event.*;

import java.util.*;


/**
 * Event generated by SoapBubbles.
 */
public class BubbleEvent extends EventObject implements java.io.Serializable {
    BubbleEvent(SoapBubbles source) {
        super(source);
    }
}
