/*
 * JSelectorPanel.java
 *
 * Created on July 23, 2001, 12:30 AM
 */
package com.lrc.swing;

/**
 * Generic Selector Panel for allowing single item user selection.
 *
 * @author fred
 * @version
 */
public abstract class JSelectorPanel extends javax.swing.JPanel {
    /** Utility field holding list of Listeners. */
    private transient java.util.ArrayList listenerList;

    /**
     * Creates new form JSelectorPanel
     */
    public JSelectorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * FormEditor.
     */
    private void initComponents() //GEN-BEGIN:initComponents
     {
        setLayout(new java.awt.BorderLayout());
    }
     //GEN-END:initComponents

    /**
     * Registers Listener to receive events.
     *
     * @param listener The listener to register.
     */
    public void addListener(com.lrc.swing.JSelectorPanel.Listener listener) {
        if (listenerList == null)
            listenerList = new java.util.ArrayList();

        listenerList.add(listener);
    }

    /**
     * Removes Listener from the list of listeners.
     *
     * @param listener The listener to remove.
     */
    public void removeListener(com.lrc.swing.JSelectorPanel.Listener listener) {
        if (listenerList != null)
            listenerList.remove(listener);
    }

    /**
     * Notifies all registered listeners about the event.
     *
     * @param event The event to be fired
     */
    protected void fireListenerSelected(Object event) {
        java.util.ArrayList list;

        if (listenerList == null)
            return;

        list = (java.util.ArrayList) listenerList.clone();

        for (int i = 0; i < list.size(); i++) {
            ((com.lrc.swing.JSelectorPanel.Listener) list.get(i)).selected(event);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public interface Listener extends java.util.EventListener {
        public void selected(Object selection);
    }
}
